name: Deploy Lambda with SAM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install AWS SAM CLI
      run: |
        pip install aws-sam-cli

    - name: Build and Deploy with SAM
      run: |
        sam build
        sam deploy --resolve-s3 --no-confirm-changeset --no-fail-on-empty-changeset \
          --stack-name PreSignedUrlStack \
          --capabilities CAPABILITY_IAM \
          --parameter-overrides UploadBucketName=presignedurluserdocimages